package com.luca.wwestatsspring.model;

public enum Stipulazione {
    NORMAL,
    EXTREMERULES,
    STEELCAGE,
    ELIMINATIONCHAMBER,
    HELLINACELL,
    LADDERMATCH,
    TABLESMATCH,
    LASTMANSTANDING,
    IQMATCH,
    IRONMANMATCH,
    TLC,
    WARGAMESMATCH,
    SPECIALGUESTREFEREE,
}
